//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaoLu.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShaoLu.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About_Header {
            get {
                return ResourceManager.GetString("About_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AboutContent 的本地化字符串。
        /// </summary>
        public static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddFindImagesStep 的本地化字符串。
        /// </summary>
        public static string AddFindImagesStep {
            get {
                return ResourceManager.GetString("AddFindImagesStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddFindImageStep 的本地化字符串。
        /// </summary>
        public static string AddFindImageStep {
            get {
                return ResourceManager.GetString("AddFindImageStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddIFStep 的本地化字符串。
        /// </summary>
        public static string AddIFStep {
            get {
                return ResourceManager.GetString("AddIFStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddImagesStep 的本地化字符串。
        /// </summary>
        public static string AddImagesStep {
            get {
                return ResourceManager.GetString("AddImagesStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddImageStep 的本地化字符串。
        /// </summary>
        public static string AddImageStep {
            get {
                return ResourceManager.GetString("AddImageStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddPopupStep 的本地化字符串。
        /// </summary>
        public static string AddPopupStep {
            get {
                return ResourceManager.GetString("AddPopupStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddTextFromFileStep 的本地化字符串。
        /// </summary>
        public static string AddTextFromFileStep {
            get {
                return ResourceManager.GetString("AddTextFromFileStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddTextMoreStep 的本地化字符串。
        /// </summary>
        public static string AddTextMoreStep {
            get {
                return ResourceManager.GetString("AddTextMoreStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddTextStep 的本地化字符串。
        /// </summary>
        public static string AddTextStep {
            get {
                return ResourceManager.GetString("AddTextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoBurn 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Step 的本地化字符串。
        /// </summary>
        public static string BtnAddStep_Content {
            get {
                return ResourceManager.GetString("BtnAddStep_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Del Step 的本地化字符串。
        /// </summary>
        public static string BtnDelStep_Content {
            get {
                return ResourceManager.GetString("BtnDelStep_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run 的本地化字符串。
        /// </summary>
        public static string BtnRun_Content {
            get {
                return ResourceManager.GetString("BtnRun_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string BtnStop_Content {
            get {
                return ResourceManager.GetString("BtnStop_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buttons 的本地化字符串。
        /// </summary>
        public static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Interval 的本地化字符串。
        /// </summary>
        public static string ClickGap {
            get {
                return ResourceManager.GetString("ClickGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clicks 的本地化字符串。
        /// </summary>
        public static string Clicks {
            get {
                return ResourceManager.GetString("Clicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition 的本地化字符串。
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConvertImageSourceToBitmapFail 的本地化字符串。
        /// </summary>
        public static string ConvertImageSourceToBitmapFail {
            get {
                return ResourceManager.GetString("ConvertImageSourceToBitmapFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crop 的本地化字符串。
        /// </summary>
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DelayBetweenKeys 的本地化字符串。
        /// </summary>
        public static string DelayBetweenKeys {
            get {
                return ResourceManager.GetString("DelayBetweenKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delimiter 的本地化字符串。
        /// </summary>
        public static string Delimiter {
            get {
                return ResourceManager.GetString("Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down 的本地化字符串。
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Image 的本地化字符串。
        /// </summary>
        public static string EditImageTitle {
            get {
                return ResourceManager.GetString("EditImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string English_Header {
            get {
                return ResourceManager.GetString("English_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExecutionFailed 的本地化字符串。
        /// </summary>
        public static string ExecutionFailed {
            get {
                return ResourceManager.GetString("ExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File_Header {
            get {
                return ResourceManager.GetString("File_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Time Interval 的本地化字符串。
        /// </summary>
        public static string FindTimeInterval {
            get {
                return ResourceManager.GetString("FindTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FontFamily 的本地化字符串。
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FontSize 的本地化字符串。
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FontStyle 的本地化字符串。
        /// </summary>
        public static string FontStyle {
            get {
                return ResourceManager.GetString("FontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Select 的本地化字符串。
        /// </summary>
        public static string FontTitle {
            get {
                return ResourceManager.GetString("FontTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image File 的本地化字符串。
        /// </summary>
        public static string Image_File {
            get {
                return ResourceManager.GetString("Image_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language_Header {
            get {
                return ResourceManager.GetString("Language_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error loading Image 的本地化字符串。
        /// </summary>
        public static string Loading_img_Warning {
            get {
                return ResourceManager.GetString("Loading_img_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinimizeOnRun 的本地化字符串。
        /// </summary>
        public static string MinimizeOnRun {
            get {
                return ResourceManager.GetString("MinimizeOnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New_Header {
            get {
                return ResourceManager.GetString("New_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No pictures selected 的本地化字符串。
        /// </summary>
        public static string No_img_Warning {
            get {
                return ResourceManager.GetString("No_img_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Matching Image 的本地化字符串。
        /// </summary>
        public static string NoMatchingImage {
            get {
                return ResourceManager.GetString("NoMatchingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Selection 的本地化字符串。
        /// </summary>
        public static string NoSelectionHint {
            get {
                return ResourceManager.GetString("NoSelectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open_Header {
            get {
                return ResourceManager.GetString("Open_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFile 的本地化字符串。
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picture similarity threshold 的本地化字符串。
        /// </summary>
        public static string Picture_similarity_threshold {
            get {
                return ResourceManager.GetString("Picture_similarity_threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Popup Text 的本地化字符串。
        /// </summary>
        public static string PopupText {
            get {
                return ResourceManager.GetString("PopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Popup Type 的本地化字符串。
        /// </summary>
        public static string PopupType {
            get {
                return ResourceManager.GetString("PopupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Question 的本地化字符串。
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        public static string Quit_Header {
            get {
                return ResourceManager.GetString("Quit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveAndBack 的本地化字符串。
        /// </summary>
        public static string SaveAndBack {
            get {
                return ResourceManager.GetString("SaveAndBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select target image 的本地化字符串。
        /// </summary>
        public static string Select_target_pic {
            get {
                return ResourceManager.GetString("Select_target_pic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Setting_Header {
            get {
                return ResourceManager.GetString("Setting_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowErrorPopup 的本地化字符串。
        /// </summary>
        public static string ShowErrorPopup {
            get {
                return ResourceManager.GetString("ShowErrorPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string SimplifiedChinese_Header {
            get {
                return ResourceManager.GetString("SimplifiedChinese_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 的本地化字符串。
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Description 的本地化字符串。
        /// </summary>
        public static string StepDescription {
            get {
                return ResourceManager.GetString("StepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Details 的本地化字符串。
        /// </summary>
        public static string StepDetails {
            get {
                return ResourceManager.GetString("StepDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FalseGoto 的本地化字符串。
        /// </summary>
        public static string StepFalseGoto {
            get {
                return ResourceManager.GetString("StepFalseGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Name 的本地化字符串。
        /// </summary>
        public static string StepName {
            get {
                return ResourceManager.GetString("StepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steps Box 的本地化字符串。
        /// </summary>
        public static string StepsBox {
            get {
                return ResourceManager.GetString("StepsBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TrueGoto 的本地化字符串。
        /// </summary>
        public static string StepTrueGoto {
            get {
                return ResourceManager.GetString("StepTrueGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Type 的本地化字符串。
        /// </summary>
        public static string StepType {
            get {
                return ResourceManager.GetString("StepType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClickImage 的本地化字符串。
        /// </summary>
        public static string StepType_ClickImage {
            get {
                return ResourceManager.GetString("StepType_ClickImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogicalIF 的本地化字符串。
        /// </summary>
        public static string StepType_LogicalIF {
            get {
                return ResourceManager.GetString("StepType_LogicalIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TypeText 的本地化字符串。
        /// </summary>
        public static string StepType_TypeText {
            get {
                return ResourceManager.GetString("StepType_TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁體中文 的本地化字符串。
        /// </summary>
        public static string TraditionalChinese_Header {
            get {
                return ResourceManager.GetString("TraditionalChinese_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type text 的本地化字符串。
        /// </summary>
        public static string Type_text {
            get {
                return ResourceManager.GetString("Type_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up 的本地化字符串。
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait Time 的本地化字符串。
        /// </summary>
        public static string WaitTime {
            get {
                return ResourceManager.GetString("WaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warn 的本地化字符串。
        /// </summary>
        public static string Warn {
            get {
                return ResourceManager.GetString("Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
