//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaoLu.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShaoLu.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About_Header {
            get {
                return ResourceManager.GetString("About_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AboutContent 的本地化字符串。
        /// </summary>
        public static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddClickPoint 的本地化字符串。
        /// </summary>
        public static string AddClickPoint {
            get {
                return ResourceManager.GetString("AddClickPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddFindImagesStep 的本地化字符串。
        /// </summary>
        public static string AddFindImagesStep {
            get {
                return ResourceManager.GetString("AddFindImagesStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddFindImageStep 的本地化字符串。
        /// </summary>
        public static string AddFindImageStep {
            get {
                return ResourceManager.GetString("AddFindImageStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddIFStep 的本地化字符串。
        /// </summary>
        public static string AddIFStep {
            get {
                return ResourceManager.GetString("AddIFStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddImagesStep 的本地化字符串。
        /// </summary>
        public static string AddImagesStep {
            get {
                return ResourceManager.GetString("AddImagesStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddImageStep 的本地化字符串。
        /// </summary>
        public static string AddImageStep {
            get {
                return ResourceManager.GetString("AddImageStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddPopupStep 的本地化字符串。
        /// </summary>
        public static string AddPopupStep {
            get {
                return ResourceManager.GetString("AddPopupStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddTextFromFileStep 的本地化字符串。
        /// </summary>
        public static string AddTextFromFileStep {
            get {
                return ResourceManager.GetString("AddTextFromFileStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddTextMoreStep 的本地化字符串。
        /// </summary>
        public static string AddTextMoreStep {
            get {
                return ResourceManager.GetString("AddTextMoreStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TextOCR 的本地化字符串。
        /// </summary>
        public static string AddTextOCRStep {
            get {
                return ResourceManager.GetString("AddTextOCRStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddTextStep 的本地化字符串。
        /// </summary>
        public static string AddTextStep {
            get {
                return ResourceManager.GetString("AddTextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add User 的本地化字符串。
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add User 的本地化字符串。
        /// </summary>
        public static string AddUserButton {
            get {
                return ResourceManager.GetString("AddUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administrator 的本地化字符串。
        /// </summary>
        public static string AdminRole {
            get {
                return ResourceManager.GetString("AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AllDelete 的本地化字符串。
        /// </summary>
        public static string AllDelete {
            get {
                return ResourceManager.GetString("AllDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AllHidden 的本地化字符串。
        /// </summary>
        public static string AllHidden {
            get {
                return ResourceManager.GetString("AllHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AllVisibale 的本地化字符串。
        /// </summary>
        public static string AllVisibale {
            get {
                return ResourceManager.GetString("AllVisibale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoBurn 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoGen 的本地化字符串。
        /// </summary>
        public static string AutoGen {
            get {
                return ResourceManager.GetString("AutoGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Step 的本地化字符串。
        /// </summary>
        public static string BtnAddStep_Content {
            get {
                return ResourceManager.GetString("BtnAddStep_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Del Step 的本地化字符串。
        /// </summary>
        public static string BtnDelStep_Content {
            get {
                return ResourceManager.GetString("BtnDelStep_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run 的本地化字符串。
        /// </summary>
        public static string BtnRun_Content {
            get {
                return ResourceManager.GetString("BtnRun_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string BtnStop_Content {
            get {
                return ResourceManager.GetString("BtnStop_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buttons 的本地化字符串。
        /// </summary>
        public static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Password 的本地化字符串。
        /// </summary>
        public static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Password 的本地化字符串。
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear OCR Region 的本地化字符串。
        /// </summary>
        public static string ClearOCRRegion {
            get {
                return ResourceManager.GetString("ClearOCRRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Interval 的本地化字符串。
        /// </summary>
        public static string ClickGap {
            get {
                return ResourceManager.GetString("ClickGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clicks 的本地化字符串。
        /// </summary>
        public static string Clicks {
            get {
                return ResourceManager.GetString("Clicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition 的本地化字符串。
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition_Add 的本地化字符串。
        /// </summary>
        public static string Condition_Add {
            get {
                return ResourceManager.GetString("Condition_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition_Remove 的本地化字符串。
        /// </summary>
        public static string Condition_Remove {
            get {
                return ResourceManager.GetString("Condition_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition_StepLineNo_Tooltip 的本地化字符串。
        /// </summary>
        public static string Condition_StepLineNo_Tooltip {
            get {
                return ResourceManager.GetString("Condition_StepLineNo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition_Value_Tooltip 的本地化字符串。
        /// </summary>
        public static string Condition_Value_Tooltip {
            get {
                return ResourceManager.GetString("Condition_Value_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode 的本地化字符串。
        /// </summary>
        public static string ConditionMode {
            get {
                return ResourceManager.GetString("ConditionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConditionMode_Hint 的本地化字符串。
        /// </summary>
        public static string ConditionMode_Hint {
            get {
                return ResourceManager.GetString("ConditionMode_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConditionMode_Label 的本地化字符串。
        /// </summary>
        public static string ConditionMode_Label {
            get {
                return ResourceManager.GetString("ConditionMode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition 的本地化字符串。
        /// </summary>
        public static string ConditionPanel {
            get {
                return ResourceManager.GetString("ConditionPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Before Run 的本地化字符串。
        /// </summary>
        public static string ConfirmBeforeRun {
            get {
                return ResourceManager.GetString("ConfirmBeforeRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete 的本地化字符串。
        /// </summary>
        public static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contents 的本地化字符串。
        /// </summary>
        public static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConvertImageSourceToBitmapFail 的本地化字符串。
        /// </summary>
        public static string ConvertImageSourceToBitmapFail {
            get {
                return ResourceManager.GetString("ConvertImageSourceToBitmapFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created At 的本地化字符串。
        /// </summary>
        public static string CreatedAtHeader {
            get {
                return ResourceManager.GetString("CreatedAtHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crop 的本地化字符串。
        /// </summary>
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Ratio Scale 的本地化字符串。
        /// </summary>
        public static string CropImage_EnableRatioScale {
            get {
                return ResourceManager.GetString("CropImage_EnableRatioScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crop Ratio: 的本地化字符串。
        /// </summary>
        public static string CropImage_RatioLabel {
            get {
                return ResourceManager.GetString("CropImage_RatioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Image 的本地化字符串。
        /// </summary>
        public static string CropImage_SaveImage {
            get {
                return ResourceManager.GetString("CropImage_SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Image 的本地化字符串。
        /// </summary>
        public static string CropImage_SelectImage {
            get {
                return ResourceManager.GetString("CropImage_SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From 的本地化字符串。
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To 的本地化字符串。
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Clicks 的本地化字符串。
        /// </summary>
        public static string DefaultClicks {
            get {
                return ResourceManager.GetString("DefaultClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self-Reference Limit 的本地化字符串。
        /// </summary>
        public static string DefaultSelfReferenceLimit {
            get {
                return ResourceManager.GetString("DefaultSelfReferenceLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Similarity Threshold 的本地化字符串。
        /// </summary>
        public static string DefaultSimilarityThreshold {
            get {
                return ResourceManager.GetString("DefaultSimilarityThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Parameters for New Steps 的本地化字符串。
        /// </summary>
        public static string DefaultStepParams {
            get {
                return ResourceManager.GetString("DefaultStepParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Timeout 的本地化字符串。
        /// </summary>
        public static string DefaultTimeout {
            get {
                return ResourceManager.GetString("DefaultTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Wait Time 的本地化字符串。
        /// </summary>
        public static string DefaultWaitTime {
            get {
                return ResourceManager.GetString("DefaultWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DelayBetweenKeys 的本地化字符串。
        /// </summary>
        public static string DelayBetweenKeys {
            get {
                return ResourceManager.GetString("DelayBetweenKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Steps 的本地化字符串。
        /// </summary>
        public static string DeleteStepTitle {
            get {
                return ResourceManager.GetString("DeleteStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Selected User 的本地化字符串。
        /// </summary>
        public static string DeleteUserButton {
            get {
                return ResourceManager.GetString("DeleteUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delimiter 的本地化字符串。
        /// </summary>
        public static string Delimiter {
            get {
                return ResourceManager.GetString("Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down 的本地化字符串。
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Image 的本地化字符串。
        /// </summary>
        public static string EditImageTitle {
            get {
                return ResourceManager.GetString("EditImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Execution Log 的本地化字符串。
        /// </summary>
        public static string EnableLog {
            get {
                return ResourceManager.GetString("EnableLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string English_Header {
            get {
                return ResourceManager.GetString("English_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter admin password 的本地化字符串。
        /// </summary>
        public static string Error_EmptyAdminPassword {
            get {
                return ResourceManager.GetString("Error_EmptyAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter admin username 的本地化字符串。
        /// </summary>
        public static string Error_EmptyAdminUsername {
            get {
                return ResourceManager.GetString("Error_EmptyAdminUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter password 的本地化字符串。
        /// </summary>
        public static string Error_EmptyPassword {
            get {
                return ResourceManager.GetString("Error_EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter username 的本地化字符串。
        /// </summary>
        public static string Error_EmptyUsername {
            get {
                return ResourceManager.GetString("Error_EmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username or password incorrect 的本地化字符串。
        /// </summary>
        public static string Error_LoginFailed {
            get {
                return ResourceManager.GetString("Error_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords do not match 的本地化字符串。
        /// </summary>
        public static string Error_PasswordMismatch {
            get {
                return ResourceManager.GetString("Error_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password must be at least 3 characters 的本地化字符串。
        /// </summary>
        public static string Error_PasswordTooShort {
            get {
                return ResourceManager.GetString("Error_PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration failed: username already exists 的本地化字符串。
        /// </summary>
        public static string Error_RegisterFailed {
            get {
                return ResourceManager.GetString("Error_RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration failed: username exists or admin approval incorrect 的本地化字符串。
        /// </summary>
        public static string Error_RegisterFailedAdmin {
            get {
                return ResourceManager.GetString("Error_RegisterFailedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executed At 的本地化字符串。
        /// </summary>
        public static string ExecutedAt {
            get {
                return ResourceManager.GetString("ExecutedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExecutionFailed 的本地化字符串。
        /// </summary>
        public static string ExecutionFailed {
            get {
                return ResourceManager.GetString("ExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution Log 的本地化字符串。
        /// </summary>
        public static string ExecutionLog {
            get {
                return ResourceManager.GetString("ExecutionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File_Header {
            get {
                return ResourceManager.GetString("File_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perform OCR after image found 的本地化字符串。
        /// </summary>
        public static string FindImage_EnableOCR {
            get {
                return ResourceManager.GetString("FindImage_EnableOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OCR Text Recognition 的本地化字符串。
        /// </summary>
        public static string FindImage_OCR_Group {
            get {
                return ResourceManager.GetString("FindImage_OCR_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FindImage_OCR_Hint 的本地化字符串。
        /// </summary>
        public static string FindImage_OCR_Hint {
            get {
                return ResourceManager.GetString("FindImage_OCR_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Time Interval 的本地化字符串。
        /// </summary>
        public static string FindTimeInterval {
            get {
                return ResourceManager.GetString("FindTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FontFamily 的本地化字符串。
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FontSize 的本地化字符串。
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FontStyle 的本地化字符串。
        /// </summary>
        public static string FontStyle {
            get {
                return ResourceManager.GetString("FontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Select 的本地化字符串。
        /// </summary>
        public static string FontTitle {
            get {
                return ResourceManager.GetString("FontTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hidden 的本地化字符串。
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image File 的本地化字符串。
        /// </summary>
        public static string Image_File {
            get {
                return ResourceManager.GetString("Image_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Infix 的本地化字符串。
        /// </summary>
        public static string Infix {
            get {
                return ResourceManager.GetString("Infix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Text 的本地化字符串。
        /// </summary>
        public static string InputText {
            get {
                return ResourceManager.GetString("InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language_Header {
            get {
                return ResourceManager.GetString("Language_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error loading Image 的本地化字符串。
        /// </summary>
        public static string Loading_img_Warning {
            get {
                return ResourceManager.GetString("Loading_img_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Login_Cancel {
            get {
                return ResourceManager.GetString("Login_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No account? 的本地化字符串。
        /// </summary>
        public static string Login_NoAccount {
            get {
                return ResourceManager.GetString("Login_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register now 的本地化字符串。
        /// </summary>
        public static string Login_RegisterNow {
            get {
                return ResourceManager.GetString("Login_RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Login 的本地化字符串。
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Retention Days 的本地化字符串。
        /// </summary>
        public static string LogRetentionDays {
            get {
                return ResourceManager.GetString("LogRetentionDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string Menu_Login {
            get {
                return ResourceManager.GetString("Menu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout ({0}) 的本地化字符串。
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinimizeOnRun 的本地化字符串。
        /// </summary>
        public static string MinimizeOnRun {
            get {
                return ResourceManager.GetString("MinimizeOnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot delete the currently logged-in user 的本地化字符串。
        /// </summary>
        public static string Msg_CannotDeleteSelf {
            get {
                return ResourceManager.GetString("Msg_CannotDeleteSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected steps? 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmDeleteSteps {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete user &apos;{0}&apos;? 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmDeleteUser {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to start running? 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmRun {
            get {
                return ResourceManager.GetString("Msg_ConfirmRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a user to delete first 的本地化字符串。
        /// </summary>
        public static string Msg_SelectUserFirst {
            get {
                return ResourceManager.GetString("Msg_SelectUserFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step &quot;{0}&quot; self-reference limit reached ({1} times), skipping execution 的本地化字符串。
        /// </summary>
        public static string Msg_SelfReferenceLimit {
            get {
                return ResourceManager.GetString("Msg_SelfReferenceLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User &apos;{0}&apos; added successfully 的本地化字符串。
        /// </summary>
        public static string Msg_UserAdded {
            get {
                return ResourceManager.GetString("Msg_UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User &apos;{0}&apos; already exists or add failed 的本地化字符串。
        /// </summary>
        public static string Msg_UserAddFailed {
            get {
                return ResourceManager.GetString("Msg_UserAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset rotation 的本地化字符串。
        /// </summary>
        public static string MultiCropImage_ResetRotationTooltip {
            get {
                return ResourceManager.GetString("MultiCropImage_ResetRotationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate crop frame 的本地化字符串。
        /// </summary>
        public static string MultiCropImage_RotateTooltip {
            get {
                return ResourceManager.GetString("MultiCropImage_RotateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New_Header {
            get {
                return ResourceManager.GetString("New_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Password 的本地化字符串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Croped picture 的本地化字符串。
        /// </summary>
        public static string No_Cropimage_Warning {
            get {
                return ResourceManager.GetString("No_Cropimage_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No picture selected 的本地化字符串。
        /// </summary>
        public static string No_img_Warning {
            get {
                return ResourceManager.GetString("No_img_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoClickPoint 的本地化字符串。
        /// </summary>
        public static string NoClickPoint {
            get {
                return ResourceManager.GetString("NoClickPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoCropImage 的本地化字符串。
        /// </summary>
        public static string NoCropImage {
            get {
                return ResourceManager.GetString("NoCropImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Matching Image 的本地化字符串。
        /// </summary>
        public static string NoMatchingImage {
            get {
                return ResourceManager.GetString("NoMatchingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Selection 的本地化字符串。
        /// </summary>
        public static string NoSelectionHint {
            get {
                return ResourceManager.GetString("NoSelectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OCR_EditRegionHint 的本地化字符串。
        /// </summary>
        public static string OCR_EditRegionHint {
            get {
                return ResourceManager.GetString("OCR_EditRegionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OCR_EditRegionTitle 的本地化字符串。
        /// </summary>
        public static string OCR_EditRegionTitle {
            get {
                return ResourceManager.GetString("OCR_EditRegionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No region selected 的本地化字符串。
        /// </summary>
        public static string OCR_NoRegion {
            get {
                return ResourceManager.GetString("OCR_NoRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No text recognized 的本地化字符串。
        /// </summary>
        public static string OCR_NoResult {
            get {
                return ResourceManager.GetString("OCR_NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OCR Region 的本地化字符串。
        /// </summary>
        public static string OCR_Region {
            get {
                return ResourceManager.GetString("OCR_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Region 的本地化字符串。
        /// </summary>
        public static string OCR_SelectRegion {
            get {
                return ResourceManager.GetString("OCR_SelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag to select OCR region, press ESC to cancel 的本地化字符串。
        /// </summary>
        public static string OCR_SelectRegionHint {
            get {
                return ResourceManager.GetString("OCR_SelectRegionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test OCR 的本地化字符串。
        /// </summary>
        public static string OCR_Test {
            get {
                return ResourceManager.GetString("OCR_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Old Password 的本地化字符串。
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open_Header {
            get {
                return ResourceManager.GetString("Open_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFile 的本地化字符串。
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picture similarity threshold 的本地化字符串。
        /// </summary>
        public static string Picture_similarity_threshold {
            get {
                return ResourceManager.GetString("Picture_similarity_threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Popup Text 的本地化字符串。
        /// </summary>
        public static string PopupText {
            get {
                return ResourceManager.GetString("PopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Popup Type 的本地化字符串。
        /// </summary>
        public static string PopupType {
            get {
                return ResourceManager.GetString("PopupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prefix 的本地化字符串。
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        public static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Question 的本地化字符串。
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        public static string Quit_Header {
            get {
                return ResourceManager.GetString("Quit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin password 的本地化字符串。
        /// </summary>
        public static string Register_AdminPassword {
            get {
                return ResourceManager.GetString("Register_AdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin username 的本地化字符串。
        /// </summary>
        public static string Register_AdminUsername {
            get {
                return ResourceManager.GetString("Register_AdminUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back to login 的本地化字符串。
        /// </summary>
        public static string Register_BackToLogin {
            get {
                return ResourceManager.GetString("Register_BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register 的本地化字符串。
        /// </summary>
        public static string Register_Button {
            get {
                return ResourceManager.GetString("Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Password 的本地化字符串。
        /// </summary>
        public static string Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("Register_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The first registered user will automatically become admin 的本地化字符串。
        /// </summary>
        public static string Register_FirstAdminHint {
            get {
                return ResourceManager.GetString("Register_FirstAdminHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already have an account? 的本地化字符串。
        /// </summary>
        public static string Register_HasAccount {
            get {
                return ResourceManager.GetString("Register_HasAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin approval required 的本地化字符串。
        /// </summary>
        public static string Register_NeedAdminApproval {
            get {
                return ResourceManager.GetString("Register_NeedAdminApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration successful, please login 的本地化字符串。
        /// </summary>
        public static string Register_Success {
            get {
                return ResourceManager.GetString("Register_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Registration 的本地化字符串。
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReloadIndex 的本地化字符串。
        /// </summary>
        public static string ReloadIndex {
            get {
                return ResourceManager.GetString("ReloadIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role 的本地化字符串。
        /// </summary>
        public static string RoleHeader {
            get {
                return ResourceManager.GetString("RoleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveAndBack 的本地化字符串。
        /// </summary>
        public static string SaveAndBack {
            get {
                return ResourceManager.GetString("SaveAndBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved 的本地化字符串。
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save File 的本地化字符串。
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select target image 的本地化字符串。
        /// </summary>
        public static string Select_target_pic {
            get {
                return ResourceManager.GetString("Select_target_pic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected User 的本地化字符串。
        /// </summary>
        public static string SelectedUser {
            get {
                return ResourceManager.GetString("SelectedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SetOCRRegion 的本地化字符串。
        /// </summary>
        public static string SetOCRRegion {
            get {
                return ResourceManager.GetString("SetOCRRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Setting_Header {
            get {
                return ResourceManager.GetString("Setting_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings_AppSettings 的本地化字符串。
        /// </summary>
        public static string Settings_AppSettings {
            get {
                return ResourceManager.GetString("Settings_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings_DaysHint 的本地化字符串。
        /// </summary>
        public static string Settings_DaysHint {
            get {
                return ResourceManager.GetString("Settings_DaysHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings_StepSettings 的本地化字符串。
        /// </summary>
        public static string Settings_StepSettings {
            get {
                return ResourceManager.GetString("Settings_StepSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowErrorPopup 的本地化字符串。
        /// </summary>
        public static string ShowErrorPopup {
            get {
                return ResourceManager.GetString("ShowErrorPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string SimplifiedChinese_Header {
            get {
                return ResourceManager.GetString("SimplifiedChinese_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 的本地化字符串。
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Description 的本地化字符串。
        /// </summary>
        public static string StepDescription {
            get {
                return ResourceManager.GetString("StepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Details 的本地化字符串。
        /// </summary>
        public static string StepDetails {
            get {
                return ResourceManager.GetString("StepDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FalseGoto 的本地化字符串。
        /// </summary>
        public static string StepFalseGoto {
            get {
                return ResourceManager.GetString("StepFalseGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StepFile 的本地化字符串。
        /// </summary>
        public static string StepFile {
            get {
                return ResourceManager.GetString("StepFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step File 的本地化字符串。
        /// </summary>
        public static string StepFileName {
            get {
                return ResourceManager.GetString("StepFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Name 的本地化字符串。
        /// </summary>
        public static string StepName {
            get {
                return ResourceManager.GetString("StepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steps Box 的本地化字符串。
        /// </summary>
        public static string StepsBox {
            get {
                return ResourceManager.GetString("StepsBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TrueGoto 的本地化字符串。
        /// </summary>
        public static string StepTrueGoto {
            get {
                return ResourceManager.GetString("StepTrueGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Type 的本地化字符串。
        /// </summary>
        public static string StepType {
            get {
                return ResourceManager.GetString("StepType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClickImage 的本地化字符串。
        /// </summary>
        public static string StepType_ClickImage {
            get {
                return ResourceManager.GetString("StepType_ClickImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogicalIF 的本地化字符串。
        /// </summary>
        public static string StepType_LogicalIF {
            get {
                return ResourceManager.GetString("StepType_LogicalIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TypeText 的本地化字符串。
        /// </summary>
        public static string StepType_TypeText {
            get {
                return ResourceManager.GetString("StepType_TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suffix 的本地化字符串。
        /// </summary>
        public static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Records 的本地化字符串。
        /// </summary>
        public static string TotalRecords {
            get {
                return ResourceManager.GetString("TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁體中文 的本地化字符串。
        /// </summary>
        public static string TraditionalChinese_Header {
            get {
                return ResourceManager.GetString("TraditionalChinese_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type text 的本地化字符串。
        /// </summary>
        public static string Type_text {
            get {
                return ResourceManager.GetString("Type_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up 的本地化字符串。
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User List 的本地化字符串。
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Management 的本地化字符串。
        /// </summary>
        public static string UserManagementTitle {
            get {
                return ResourceManager.GetString("UserManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string UsernameHeader {
            get {
                return ResourceManager.GetString("UsernameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard User 的本地化字符串。
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait Time 的本地化字符串。
        /// </summary>
        public static string WaitTime {
            get {
                return ResourceManager.GetString("WaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warn 的本地化字符串。
        /// </summary>
        public static string Warn {
            get {
                return ResourceManager.GetString("Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
