//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaoLu.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShaoLu.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddIFStep 的本地化字符串。
        /// </summary>
        public static string AddIFStep {
            get {
                return ResourceManager.GetString("AddIFStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddImageStep 的本地化字符串。
        /// </summary>
        public static string AddImageStep {
            get {
                return ResourceManager.GetString("AddImageStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddTextStep 的本地化字符串。
        /// </summary>
        public static string AddTextStep {
            get {
                return ResourceManager.GetString("AddTextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoBurn 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Step 的本地化字符串。
        /// </summary>
        public static string BtnAddStep_Content {
            get {
                return ResourceManager.GetString("BtnAddStep_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Del Step 的本地化字符串。
        /// </summary>
        public static string BtnDelStep_Content {
            get {
                return ResourceManager.GetString("BtnDelStep_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run 的本地化字符串。
        /// </summary>
        public static string BtnRun_Content {
            get {
                return ResourceManager.GetString("BtnRun_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string BtnStop_Content {
            get {
                return ResourceManager.GetString("BtnStop_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crop 的本地化字符串。
        /// </summary>
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Image 的本地化字符串。
        /// </summary>
        public static string EditImageTitle {
            get {
                return ResourceManager.GetString("EditImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string English_Header {
            get {
                return ResourceManager.GetString("English_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File_Header {
            get {
                return ResourceManager.GetString("File_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image File 的本地化字符串。
        /// </summary>
        public static string Image_File {
            get {
                return ResourceManager.GetString("Image_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language_Header {
            get {
                return ResourceManager.GetString("Language_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error loading Image 的本地化字符串。
        /// </summary>
        public static string Loading_img_Warning {
            get {
                return ResourceManager.GetString("Loading_img_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New_Header {
            get {
                return ResourceManager.GetString("New_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No pictures selected 的本地化字符串。
        /// </summary>
        public static string No_img_Warning {
            get {
                return ResourceManager.GetString("No_img_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Selection 的本地化字符串。
        /// </summary>
        public static string NoSelectionHint {
            get {
                return ResourceManager.GetString("NoSelectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open_Header {
            get {
                return ResourceManager.GetString("Open_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picture similarity threshold 的本地化字符串。
        /// </summary>
        public static string Picture_similarity_threshold {
            get {
                return ResourceManager.GetString("Picture_similarity_threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        public static string Quit_Header {
            get {
                return ResourceManager.GetString("Quit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select target image 的本地化字符串。
        /// </summary>
        public static string Select_target_pic {
            get {
                return ResourceManager.GetString("Select_target_pic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Setting_Header {
            get {
                return ResourceManager.GetString("Setting_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string SimplifiedChinese_Header {
            get {
                return ResourceManager.GetString("SimplifiedChinese_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Description 的本地化字符串。
        /// </summary>
        public static string StepDescription {
            get {
                return ResourceManager.GetString("StepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Details 的本地化字符串。
        /// </summary>
        public static string StepDetails {
            get {
                return ResourceManager.GetString("StepDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Name 的本地化字符串。
        /// </summary>
        public static string StepName {
            get {
                return ResourceManager.GetString("StepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steps Box 的本地化字符串。
        /// </summary>
        public static string StepsBox {
            get {
                return ResourceManager.GetString("StepsBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step Type 的本地化字符串。
        /// </summary>
        public static string StepType {
            get {
                return ResourceManager.GetString("StepType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClickImage 的本地化字符串。
        /// </summary>
        public static string StepType_ClickImage {
            get {
                return ResourceManager.GetString("StepType_ClickImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogicalIF 的本地化字符串。
        /// </summary>
        public static string StepType_LogicalIF {
            get {
                return ResourceManager.GetString("StepType_LogicalIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TypeText 的本地化字符串。
        /// </summary>
        public static string StepType_TypeText {
            get {
                return ResourceManager.GetString("StepType_TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁體中文 的本地化字符串。
        /// </summary>
        public static string TraditionalChinese_Header {
            get {
                return ResourceManager.GetString("TraditionalChinese_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Warning_Title {
            get {
                return ResourceManager.GetString("Warning_Title", resourceCulture);
            }
        }
    }
}
